### ISSUE TITLE
the tool wase useful for too long till this happen 

### ISSUE THREAD

**Issue by massam0078** [f-o/MEGA-Account-Generator#12]
![IMG-20241225-WA0001.jpg](https://github.com/user-attachments/assets/fb326963-9f54-483a-a2cb-91209d1da214)

**Comment by f-o** [comment]
This seems to be a duplicate of #4.
You can go there to read a bit more about the problem.

In short, MEGA is trying to combat multiple-account generation, and has most likely banned the current mail.tm domain.
Mail.tm does rotate the domain, once in a while, but it's always gonna be a cat-against-the-mouse type of situation.

I'm debating whether I want to support multiple temp-email backends, which would allow the script to bypass these type of bans.

**Comment by massam0078** [comment]
our work in between you golden hands . hope you can fix it and launch a new update
